# Generated by Django 3.2.12 on 2022-02-26 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_auto_20220226_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
